### ISSUE TITLE
I do not want to require application/json

### ISSUE THREAD

**Issue by farzher** [expressjs/body-parser#76]
Or any content-type at all. I already defined my routes, if this one gets hit I want to parse the body as JSON.

Is this an option or should I just not use `bodyParser.json()`

**Comment by dougwilson** [comment]
`bodyParser.json({ type: '*/*' })`

**Comment by dougwilson** [comment]
Sorry, didn't mean to close this, especially since I haven't tested if that's what you want :)

**Comment by dougwilson** [comment]
It seems like that may not work (and it definitely won't work if the `Content-Type` header is completely missing). I think it's fine to support your use-case, so we can add it in as an option.

**Comment by farzher** [comment]
Yeah that doesn't seem to work. I found the `type` option but wasn't able to do what I wanted with it.

Requiring a content-type is just annoying for the users of my API. It's totally unnecessary in my case.

An option to ignore the `content-type` would be great.

**Comment by dougwilson** [comment]
In the meantime, this is the work-around:
```js
var bodyParser = require('body-parser')

function jsonParse() {
  var parse = bodyParser.json()
  return function (req, res, next) {
    req.headers['content-type'] = 'application/json'
    parse(req, res, next)
  }
}
```

Then, in your code:
```js
var jsonParser = jsonParse()

app.post('/my/route', jsonParser, function (req, res) {
  res.send('hello!')
})
```

**Comment by farzher** [comment]
I see, ty.

Oh also, how do I know if the body is empty? If body is empty you return an empty object `{}` and I have no idea if they actually sent an empty object or nothing at all.

I see in your source code it says `// TODO: maybe make this configurable or part of "strict" option`, lol.
https://github.com/expressjs/body-parser/blob/master/lib/types/json.js#L64

**Comment by dougwilson** [comment]
> Oh also, how do I know if the body is empty? 

This feature is only available on v2, which is still in progress (there is a branch on here to see the code). You can use the type-is library's hasBody method, though.

**Comment by dougwilson** [comment]
It's unfortunate that we had to default an empty body to {}, but it's for the same reason people feel it's too difficult to send a content-type header with their request.

**Comment by snakamura** [comment]
I'd also like to have that option for raw parser, too. I'm trying to allow a client to put a file with an arbitrary Content-Type, but body-parser doesn't allow it without your workaround.

**Comment by dougwilson** [comment]
Hm... So I was originally thinking about `type: '*'`, but then realized that kinda means "any content type", but wouldn't logically include "no content type" :/ I'm trying to think of a good API. Right now I'm debating moving "any content type" to perhaps be `type: '*/*'` and "any/no content type" to perhaps be `type: '*'`, or something... Normally I would do `type: null` or `type: undefined`, but both of those are too ingrained to change the meaning without a major version bump right now.

**Comment by dougwilson** [comment]
Any thoughts on the syntax?

**Comment by snakamura** [comment]
`*/*` for any content type and `*` for any/no content type would be fine. I'm not sure if we need to distinguish these two cases though.

Another idea is that allowing to specify a function that takes a content type as a parameter and returns boolean as type property. If a client specify a function, body-parser will call this function to check the content type instead of using type-is.

**Comment by dougwilson** [comment]
> If a client specify a function, body-parser will call this function to check the content type instead of using type-is.

I like this :) Something like this is _so core_, since it means that a solution to this issue would have already existed.

Great, I appreciate the follow up, @snakamura ! I think I have enough feedback to get a new version out this week with the support.

**Comment by farzher** [comment]
oh, duh! a function is a great idea, it's more powerful and easier to understand.

`function(){return false}` lol

**Comment by dougwilson** [comment]
Yep. IDK why I kept overlooking that :D

**Comment by dougwilson** [comment]
Just to give an update on this: I'm just finalizing some details on how the function is going to work; the `*/*` support is already on `master`, though. As for the function, I'm thinking of calling it as `fn(req)` and expecting `true` to be returned (or maybe just a truthy value?) to parse it. The function won't be called if `typeis.hasBody(req)` returns false, though.

**Comment by dougwilson** [comment]
Ok, this has _finally_ been addressed :)

@farzher for your use-case, you would use the following:
```js
// create a json parser that parses any request with a body
var parsejson = bodyParser.json({ type: function () { return true } })

// ... later

app.post('/path', parsejson, function (req, res) {
  res.send('hi!')
})
```

@snakamura for your use-case, you would use the following:
```js
// create a json parser that parses any request with a body
var getbody = bodyParser.raw({ type: '*/*' })

// ... later

app.post('/path', getbody, function (req, res) {
  res.send('hi!')
})
```

**Comment by dougwilson** [comment]
This has been published to npm as 1.12.0

**Comment by snakamura** [comment]
I've verified that it worked as expected using `*/*` with body-parser 1.12.0 and type-is 1.6.0. Thanks!

**Comment by TheSavior** [comment]
Hey guys, I've been struggling with this problem when upgrading from 1.3.1 to 1.4.0 (the minimum version switch to get this to happen). I too have clients calling an API that I don't want to require setting the content type.

If I call
```javascript
app.use(bodyParser.json({
    type: function(req) {
      console.log(req);
      return true;
    }
  }));
```
Nothing gets printed and I get the error
```
TypeError: undefined is not a function
    at normalize (/node_modules/body-parser/node_modules/type-is/index.js:154:35)
    at typeis (/node_modules/body-parser/node_modules/type-is/index.js:50:19)
    at typeofrequest (/node_modules/body-parser/node_modules/type-is/index.js:127:10)
    at jsonParser (/node_modules/body-parser/lib/types/json.js:71:10)
```

If I call
```javascript
app.use(bodyParser.json({
    type: ['json', '', '*']
  }));
```

I get
```
Error: specified encoding unsupported
    at makeError (/node_modules/body-parser/node_modules/raw-body/index.js:171:15)
    at getDecoder (/node_modules/body-parser/node_modules/raw-body/index.js:160:15)
    at module.exports (/node_modules/body-parser/node_modules/raw-body/index.js:77:15)
    at read (/node_modules/body-parser/lib/read.js:65:3)
```
which is the same error as if I just called `app.use(bodyParser.json());`

Any ideas?

**Comment by dougwilson** [comment]
@TheSavior please open a new issue instead of tacking on to old issues. I'd be happy to assist you in a new issue.

**Comment by dougwilson** [comment]
Also, @TheSavior , an error like `Error: unsupported charset "UTF-8"` typically means your `body-parser` install is simply corrupted. You should `npm uninstall body-parser && npm cache clean && npm install body-parser` to see if that fixes the issue. I'm locking this thread for now; if you need to post anything follow up, please feel free to create a new thread. I'm just trying to prevent old, finished threads from getting hijacked.
